// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package genaicommons.proxies;

/**
 * The response returned by model contains token usage metrics.
 * Note: Not all connectors or models might support token usage metrics.
 */
public class EmbeddingsResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject embeddingsResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GenAICommons.EmbeddingsResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PromptTokens("PromptTokens"),
		TotalTokens("TotalTokens"),
		DurationMilliseconds("DurationMilliseconds"),
		EmbeddingsResponse_ChunkCollection("GenAICommons.EmbeddingsResponse_ChunkCollection");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmbeddingsResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmbeddingsResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject embeddingsResponseMendixObject)
	{
		if (embeddingsResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, embeddingsResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.embeddingsResponseMendixObject = embeddingsResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmbeddingsResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static genaicommons.proxies.EmbeddingsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return genaicommons.proxies.EmbeddingsResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static genaicommons.proxies.EmbeddingsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new genaicommons.proxies.EmbeddingsResponse(context, mendixObject);
	}

	public static genaicommons.proxies.EmbeddingsResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return genaicommons.proxies.EmbeddingsResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PromptTokens
	 */
	public final java.lang.Integer getPromptTokens()
	{
		return getPromptTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of PromptTokens
	 */
	public final java.lang.Integer getPromptTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PromptTokens.toString());
	}

	/**
	 * Set value of PromptTokens
	 * @param prompttokens
	 */
	public final void setPromptTokens(java.lang.Integer prompttokens)
	{
		setPromptTokens(getContext(), prompttokens);
	}

	/**
	 * Set value of PromptTokens
	 * @param context
	 * @param prompttokens
	 */
	public final void setPromptTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer prompttokens)
	{
		getMendixObject().setValue(context, MemberNames.PromptTokens.toString(), prompttokens);
	}

	/**
	 * @return value of TotalTokens
	 */
	public final java.lang.Integer getTotalTokens()
	{
		return getTotalTokens(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTokens
	 */
	public final java.lang.Integer getTotalTokens(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalTokens.toString());
	}

	/**
	 * Set value of TotalTokens
	 * @param totaltokens
	 */
	public final void setTotalTokens(java.lang.Integer totaltokens)
	{
		setTotalTokens(getContext(), totaltokens);
	}

	/**
	 * Set value of TotalTokens
	 * @param context
	 * @param totaltokens
	 */
	public final void setTotalTokens(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaltokens)
	{
		getMendixObject().setValue(context, MemberNames.TotalTokens.toString(), totaltokens);
	}

	/**
	 * @return value of DurationMilliseconds
	 */
	public final java.lang.Integer getDurationMilliseconds()
	{
		return getDurationMilliseconds(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationMilliseconds
	 */
	public final java.lang.Integer getDurationMilliseconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DurationMilliseconds.toString());
	}

	/**
	 * Set value of DurationMilliseconds
	 * @param durationmilliseconds
	 */
	public final void setDurationMilliseconds(java.lang.Integer durationmilliseconds)
	{
		setDurationMilliseconds(getContext(), durationmilliseconds);
	}

	/**
	 * Set value of DurationMilliseconds
	 * @param context
	 * @param durationmilliseconds
	 */
	public final void setDurationMilliseconds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer durationmilliseconds)
	{
		getMendixObject().setValue(context, MemberNames.DurationMilliseconds.toString(), durationmilliseconds);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmbeddingsResponse_ChunkCollection
	 */
	public final genaicommons.proxies.ChunkCollection getEmbeddingsResponse_ChunkCollection() throws com.mendix.core.CoreException
	{
		return getEmbeddingsResponse_ChunkCollection(getContext());
	}

	/**
	 * @param context
	 * @return value of EmbeddingsResponse_ChunkCollection
	 * @throws com.mendix.core.CoreException
	 */
	public final genaicommons.proxies.ChunkCollection getEmbeddingsResponse_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		genaicommons.proxies.ChunkCollection result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmbeddingsResponse_ChunkCollection.toString());
		if (identifier != null) {
			result = genaicommons.proxies.ChunkCollection.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmbeddingsResponse_ChunkCollection
	 * @param embeddingsresponse_chunkcollection
	 */
	public final void setEmbeddingsResponse_ChunkCollection(genaicommons.proxies.ChunkCollection embeddingsresponse_chunkcollection)
	{
		setEmbeddingsResponse_ChunkCollection(getContext(), embeddingsresponse_chunkcollection);
	}

	/**
	 * Set value of EmbeddingsResponse_ChunkCollection
	 * @param context
	 * @param embeddingsresponse_chunkcollection
	 */
	public final void setEmbeddingsResponse_ChunkCollection(com.mendix.systemwideinterfaces.core.IContext context, genaicommons.proxies.ChunkCollection embeddingsresponse_chunkcollection)
	{
		if (embeddingsresponse_chunkcollection == null) {
			getMendixObject().setValue(context, MemberNames.EmbeddingsResponse_ChunkCollection.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmbeddingsResponse_ChunkCollection.toString(), embeddingsresponse_chunkcollection.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return embeddingsResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final genaicommons.proxies.EmbeddingsResponse that = (genaicommons.proxies.EmbeddingsResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
