// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Function_ExecuteMicroflow extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Function;
	private genaicommons.proxies.Function Function;
	private java.lang.String Arguments;

	public Function_ExecuteMicroflow(IContext context, IMendixObject Function, java.lang.String Arguments)
	{
		super(context);
		this.__Function = Function;
		this.Arguments = Arguments;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Function = this.__Function == null ? null : genaicommons.proxies.Function.initialize(getContext(), __Function);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Function_ExecuteMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
