// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Use this microflow operation to execute an image generations API call based on a prompt string input. The Response object needs to be processed to create a single or multiple images.
 * 
 * Inputs:
 * - DeployedModel: The DeployedModel entity replaces the Connection entity. It contains the name of the microflow to be executed for the specified model and other information relevant to connect to a model. The OutputModality needs to be Image.
 * - UserPrompt: String that describes the content of the image that is generated.
 * - ImageOptions (optional): This can be used to pass optional request attributes.
 * 
 * Outputs:
 * - Response: This is a Response object pointing to a message with a FileCollection containing one or multiple FileContent objects. These FileContent objects can be converted into a single or multiple images using the response handling microflows.
 */
public class ImageGenerations extends CustomJavaAction<IMendixObject>
{
	private java.lang.String UserPrompt;
	private IMendixObject __DeployedModel;
	private genaicommons.proxies.DeployedModel DeployedModel;
	private IMendixObject __ImageOptions;
	private genaicommons.proxies.ImageOptions ImageOptions;

	public ImageGenerations(IContext context, java.lang.String UserPrompt, IMendixObject DeployedModel, IMendixObject ImageOptions)
	{
		super(context);
		this.UserPrompt = UserPrompt;
		this.__DeployedModel = DeployedModel;
		this.__ImageOptions = ImageOptions;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.DeployedModel = this.__DeployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), __DeployedModel);

		this.ImageOptions = this.__ImageOptions == null ? null : genaicommons.proxies.ImageOptions.initialize(getContext(), __ImageOptions);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImageGenerations";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
