// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Tool_ExecuteMicroflow extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Tool;
	private genaicommons.proxies.Tool Tool;
	private IMendixObject __Request;
	private genaicommons.proxies.Request Request;
	private java.lang.String Arguments;

	public Tool_ExecuteMicroflow(IContext context, IMendixObject Tool, IMendixObject Request, java.lang.String Arguments)
	{
		super(context);
		this.__Tool = Tool;
		this.__Request = Request;
		this.Arguments = Arguments;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Tool = this.__Tool == null ? null : genaicommons.proxies.Tool.initialize(getContext(), __Tool);

		this.Request = this.__Request == null ? null : genaicommons.proxies.Request.initialize(getContext(), __Request);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Tool_ExecuteMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
