// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package synthiaconnector.proxies;

public class KnowledgeBase
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SynthiaConnector.KnowledgeBase";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		KnowledgeBase_ConfigurationKnowledgeBase("SynthiaConnector.KnowledgeBase_ConfigurationKnowledgeBase");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected KnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject knowledgeBaseMendixObject)
	{
		if (knowledgeBaseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, knowledgeBaseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.knowledgeBaseMendixObject = knowledgeBaseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'KnowledgeBase.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static synthiaconnector.proxies.KnowledgeBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return synthiaconnector.proxies.KnowledgeBase.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static synthiaconnector.proxies.KnowledgeBase initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new synthiaconnector.proxies.KnowledgeBase(context, mendixObject);
	}

	public static synthiaconnector.proxies.KnowledgeBase load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return synthiaconnector.proxies.KnowledgeBase.initialize(context, mendixObject);
	}

	public static java.util.List<synthiaconnector.proxies.KnowledgeBase> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> synthiaconnector.proxies.KnowledgeBase.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KnowledgeBase_ConfigurationKnowledgeBase
	 */
	public final synthiaconnector.proxies.ConfigurationKnowledgeBase getKnowledgeBase_ConfigurationKnowledgeBase() throws com.mendix.core.CoreException
	{
		return getKnowledgeBase_ConfigurationKnowledgeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeBase_ConfigurationKnowledgeBase
	 * @throws com.mendix.core.CoreException
	 */
	public final synthiaconnector.proxies.ConfigurationKnowledgeBase getKnowledgeBase_ConfigurationKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		synthiaconnector.proxies.ConfigurationKnowledgeBase result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KnowledgeBase_ConfigurationKnowledgeBase.toString());
		if (identifier != null) {
			result = synthiaconnector.proxies.ConfigurationKnowledgeBase.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KnowledgeBase_ConfigurationKnowledgeBase
	 * @param knowledgebase_configurationknowledgebase
	 */
	public final void setKnowledgeBase_ConfigurationKnowledgeBase(synthiaconnector.proxies.ConfigurationKnowledgeBase knowledgebase_configurationknowledgebase)
	{
		setKnowledgeBase_ConfigurationKnowledgeBase(getContext(), knowledgebase_configurationknowledgebase);
	}

	/**
	 * Set value of KnowledgeBase_ConfigurationKnowledgeBase
	 * @param context
	 * @param knowledgebase_configurationknowledgebase
	 */
	public final void setKnowledgeBase_ConfigurationKnowledgeBase(com.mendix.systemwideinterfaces.core.IContext context, synthiaconnector.proxies.ConfigurationKnowledgeBase knowledgebase_configurationknowledgebase)
	{
		if (knowledgebase_configurationknowledgebase == null) {
			getMendixObject().setValue(context, MemberNames.KnowledgeBase_ConfigurationKnowledgeBase.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KnowledgeBase_ConfigurationKnowledgeBase.toString(), knowledgebase_configurationknowledgebase.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return knowledgeBaseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final synthiaconnector.proxies.KnowledgeBase that = (synthiaconnector.proxies.KnowledgeBase) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
